### PR TITLE
changed heirarchy

### PR DESCRIPTION
**Pull request by benwaffle**
com.remote.remote2d has the folders:
engine - engine files
editor - editor files
extra - test game files

### CODE REVIEW

**Comment by benwaffle** [comment]
princeton confirms that there should be no conflicts

**Comment by Flafla2** [comment]
Looks good, except I put it on a creative commons license for a reason.

**Comment by Flafla2** [comment]
Also the .gitignore should have .metadata files as well

**Comment by Flafla2** [comment]
Also I'm not a fan of the (automatic?) stylistic changes you have going.  The entire engine so far is:

public void method()
{
    //...
}

furthermore these automatic changes are making it difficult to see what exactly is going on.  Please turn these off.

**Comment by Flafla2** [comment]
Seriously please turn off whatever code managing software you have on right now.  It is literally changing EVERY line, and I can't tell what you are actually changing!

**Comment by Flafla2** [comment]
Yeah, I can't approve this until you get all of the unneeded clutter out of it.  Also, please be more descriptive in your commit names.  "working on stuff" and "_" is really unacceptable.

**Comment by benwaffle** [comment]
you aren't consistent with your code style. sometimes brackets have their own line, sometimes they don't, sometimes everything is on one line such as `try{Thread.sleep(1);}catch(Exception e){e.printStackTrace();}`

Regarding the style, the opening of a code block should be one line and the closing of a code block should be one line. Example:

``` Java
while(true){ //opening
  //do stuff
} //closing
```

**Comment by benwaffle** [comment]
i'm going to close this and create pull requests with concrete changes

**Pull request closed without merging**
